import catalogue from "@/data/imported-product-catalogue.json";
import type { Product } from "@/lib/types";

/**
 * Generated by scripts/import-product-catalogue.mjs. It is deliberately kept
 * separate from the hand-curated base catalogue so future imports can enrich
 * rather than overwrite local editorial content.
 */
const displayBrand: Record<string, string> = { Geminy: "GEMINY" };

export const importedProducts = (catalogue as { products: Product[] }).products.map((product) => ({
  ...product,
  brand: displayBrand[product.brand] ?? product.brand,
}));
